name: xLobby
author: XenoDEV
version: '2.3-Snapshot'
api-version: 1.20

softdepend:
  - NoteBlockAPI
  - ParticleNativeAPI

main: de.xenodev.xLobby

commands:
  location:
    description: Setze die Location der Lobby
  test:
    description: Only a test
  sqladmin:
    description: Setze verschiedene MySQL-Werte
  event:
    description: Setze das Event der Lobby
  redeem:
    description: Hole dir über Codes belohnungen ab